// Pre-generate responsive AVIF + WebP variants for every raster image actually
// referenced by the site (in mirror blobs, markdown articles, components, CSS).
// The originals stay as the fallback. Variant names match the Picture component
// convention: <name>-<width>.avif / .webp.
//
//   node scripts/images.mjs            # generate missing variants
//   node scripts/images.mjs --force    # regenerate all
//
// sharp's prebuilt binary loads fine here (it just can't build from source, so
// installs use --ignore-scripts). Run after adding/replacing an upload.
import sharp from 'sharp';
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { execSync } from 'node:child_process';

const WIDTHS = [640, 1024, 1440, 1920];
const FORCE = process.argv.includes('--force');
const PUB = 'public';

// 1) Collect every /assets/... .jpg/.jpeg/.png referenced anywhere we render.
const sources = execSync(
  'find _mirror src public/assets -type f \\( -name "*.html" -o -name "*.md" -o -name "*.astro" -o -name "*.css" \\)',
  { encoding: 'utf8' }
).trim().split('\n').filter(Boolean);

const used = new Set();
for (const f of sources) {
  const txt = readFileSync(f, 'utf8');
  for (const m of txt.matchAll(/\/assets\/[^)"'\s]+?\.(?:jpe?g|png)/gi)) used.add(m[0]);
}

const variant = (rel, w, ext) => `${PUB}${rel}`.replace(/\.(jpe?g|png)$/i, `-${w}.${ext}`);
const fresh = (out, src) => existsSync(out) && !FORCE && statSync(out).mtimeMs >= statSync(src).mtimeMs;

let made = 0, skipped = 0, missing = 0;
const manifest = {};
for (const rel of [...used].sort()) {
  const src = `${PUB}${rel}`;
  if (!existsSync(src)) { missing++; continue; }
  const meta = await sharp(src).metadata();
  // Emit each standard width below the source, plus one at the source width
  // itself (capped at 1920) so there's always an optimized full-resolution
  // variant — never just a single small one.
  const CAP = 1920;
  const full = Math.min(meta.width, CAP);
  let targets = [...new Set([...WIDTHS.filter((w) => w < meta.width && w <= CAP), full])].sort((a, b) => a - b);
  manifest[rel] = targets;

  for (const w of targets) {
    for (const [ext, opts] of [['avif', { quality: 52 }], ['webp', { quality: 78 }]]) {
      const out = variant(rel, w, ext);
      if (fresh(out, src)) { skipped++; continue; }
      const pipe = sharp(src);
      if (w < meta.width) pipe.resize(w);
      await pipe[ext](opts).toFile(out);
      made++;
    }
  }
}
// Manifest of generated widths per image, imported by src/lib/img.ts (the
// Cloudflare prerender runtime has no node:fs, so the helper can't scan at
// render time — it reads this instead).
const sorted = Object.fromEntries(Object.entries(manifest).sort());
writeFileSync(
  'src/data/image-variants.ts',
  '// AUTO-GENERATED by scripts/images.mjs — widths of the AVIF/WebP variants\n' +
  '// available for each upload (used by src/lib/img.ts background image-set()).\n' +
  `export const imageVariants: Record<string, number[]> = ${JSON.stringify(sorted, null, 2)};\n`
);
console.log(`images: ${used.size} referenced, ${made} variants written, ${skipped} up-to-date${missing ? `, ${missing} missing source(s)` : ''}; manifest: ${Object.keys(sorted).length} entries.`);
