// AUTO-GENERATED by scripts/extract-articles.mjs — single source of truth for the
// resource articles. Card data powers both each article's related-posts and the
// /resources index. The prose body of each article lives in _mirror/<slug>.article.html.

export interface Article {
  slug: string;
  heroTitle: string;   // <h1> in the article hero
  heroImage: string;   // hero background image url
  cardTitle: string;   // title shown on post cards
  thumbnail: string;   // post-card thumbnail url
  excerpt: string;     // post-card excerpt
  meta: string;        // post-card meta line, e.g. "Mar 3rd 2026 By Safe Harbours"
  related: string[];   // ordered slugs shown in this article's related-posts
}

export const articles: Record<string, Article> = {
  '4-best-childrens-foster-agencies-in-hamilton': {
    slug: '4-best-childrens-foster-agencies-in-hamilton',
    heroTitle: '4 Best Children&#8217;s Foster Agencies in Hamilton',
    heroImage: '/assets/uploads/2026/02/best_foster3.jpg',
    cardTitle: '4 Best Children&#8217;s Foster Agencies in Hamilton',
    thumbnail: '/assets/uploads/2026/02/best_foster3.jpg',
    excerpt: 'Choosing a foster agency is one of the most important decisions you’ll make as a prospective foster parent, because the...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', 'what-is-it-like-to-be-a-foster-parent-guide-for-ontario'],
  },
  '5-best-childrens-foster-agencies-in-mississauga': {
    slug: '5-best-childrens-foster-agencies-in-mississauga',
    heroTitle: '5 Best Children&#8217;s Foster Agencies in Mississauga',
    heroImage: '/assets/uploads/2026/02/best_foster2.jpg',
    cardTitle: '5 Best Children&#8217;s Foster Agencies in Mississauga',
    thumbnail: '/assets/uploads/2026/02/best_foster2.jpg',
    excerpt: 'Choosing the right foster agency is a key decision when you are considering becoming a foster parent, and this guide...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '4-best-childrens-foster-agencies-in-hamilton', 'what-is-it-like-to-be-a-foster-parent-guide-for-ontario'],
  },
  'best-childrens-foster-agencies-in-toronto': {
    slug: 'best-childrens-foster-agencies-in-toronto',
    heroTitle: '6 Best Children&#8217;s Foster Agencies in Toronto',
    heroImage: '/assets/uploads/2026/02/best_foster1.jpg',
    cardTitle: '6 Best Children&#8217;s Foster Agencies in Toronto',
    thumbnail: '/assets/uploads/2026/02/best_foster1.jpg',
    excerpt: 'Foster care in Toronto is built around a shared responsibility between Children’s Aid Societies and licensed foster agencies, all working...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton', 'what-is-it-like-to-be-a-foster-parent-guide-for-ontario'],
  },
  'can-you-end-a-foster-placement-if-it-isnt-working-out-yes': {
    slug: 'can-you-end-a-foster-placement-if-it-isnt-working-out-yes',
    heroTitle: 'Can You End a Foster Placement If It Isn’t Working Out? &#8211; Yes',
    heroImage: '/assets/uploads/2026/02/foster_worried2.jpg',
    cardTitle: 'Can You End a Foster Placement If It Isn’t Working Out? &#8211; Yes',
    thumbnail: '/assets/uploads/2026/02/foster_worried2.jpg',
    excerpt: 'Foster care is built on the idea of fit, and the system recognizes that even well-prepared, caring homes may encounter...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'can-you-request-a-different-foster-child-if-it-isnt-working-out-yes': {
    slug: 'can-you-request-a-different-foster-child-if-it-isnt-working-out-yes',
    heroTitle: 'Can You Request a Different Foster Child If It Isn’t Working Out? Yes',
    heroImage: '/assets/uploads/2026/02/foster_worried1.jpg',
    cardTitle: 'Can You Request a Different Foster Child If It Isn’t Working Out? Yes',
    thumbnail: '/assets/uploads/2026/02/foster_worried1.jpg',
    excerpt: 'Sometimes Foster Placements Don’t Work Out Sometimes a foster placement is not the right fit, even when you prepare carefully...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'costs-and-compensation-of-being-a-foster-parent-in-ontario': {
    slug: 'costs-and-compensation-of-being-a-foster-parent-in-ontario',
    heroTitle: 'Costs and Compensation of Being a Foster Parent in Ontario',
    heroImage: '/assets/uploads/2025/10/compensation.jpg',
    cardTitle: 'Costs and Compensation of Being a Foster Parent in Ontario',
    thumbnail: '',
    excerpt: '',
    meta: '',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'eligibility-and-requirements-for-becoming-a-foster-parent-in-ontario': {
    slug: 'eligibility-and-requirements-for-becoming-a-foster-parent-in-ontario',
    heroTitle: 'Eligibility and Requirements for Becoming a Foster Parent in Ontario',
    heroImage: '/assets/uploads/2026/02/foster6.jpg',
    cardTitle: 'Eligibility and Requirements for Becoming a Foster Parent in Ontario',
    thumbnail: '/assets/uploads/2026/02/foster6.jpg',
    excerpt: 'What Does It Mean to Be a Foster Parent Becoming a foster parent in Ontario means opening your home to...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'getting-started-with-fostering-in-ontario': {
    slug: 'getting-started-with-fostering-in-ontario',
    heroTitle: 'Getting Started with Fostering in Ontario &#8211; A Full Guide',
    heroImage: '/assets/uploads/2025/10/getting-started.jpg',
    cardTitle: 'Getting Started with Fostering in Ontario &#8211; A Full Guide',
    thumbnail: '',
    excerpt: '',
    meta: '',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'how-to-choose-a-foster-agency-a-guide-for-ontario': {
    slug: 'how-to-choose-a-foster-agency-a-guide-for-ontario',
    heroTitle: 'How to Choose a Foster Agency &#8211; A Guide for Ontario',
    heroImage: '/assets/uploads/2026/02/foster3.jpg',
    cardTitle: 'How to Choose a Foster Agency &#8211; A Guide for Ontario',
    thumbnail: '/assets/uploads/2026/02/foster3.jpg',
    excerpt: 'Choosing a foster agency is one of the most important decisions you will make as a prospective foster parent, because...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'is-fostering-right-for-you': {
    slug: 'is-fostering-right-for-you',
    heroTitle: 'Is Fostering Right for You?',
    heroImage: '/assets/uploads/2025/10/right-for-you.jpg',
    cardTitle: 'Is Fostering Right for You?',
    thumbnail: '',
    excerpt: '',
    meta: '',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'is-it-hard-to-become-a-foster-parent-in-ontario': {
    slug: 'is-it-hard-to-become-a-foster-parent-in-ontario',
    heroTitle: 'Is It Hard to Become a Foster Parent in Ontario?',
    heroImage: '/assets/uploads/2026/02/foster2.jpg',
    cardTitle: 'Is It Hard to Become a Foster Parent in Ontario?',
    thumbnail: '/assets/uploads/2026/02/foster2.jpg',
    excerpt: 'Becoming a foster parent in Ontario can be challenging, but it is also follows a clear and structured process designed...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
  'what-is-it-like-to-be-a-foster-parent-guide-for-ontario': {
    slug: 'what-is-it-like-to-be-a-foster-parent-guide-for-ontario',
    heroTitle: 'What is it Like to be a Foster Parent? &#8211; A Guide for Ontario',
    heroImage: '/assets/uploads/2026/02/foster1.jpg',
    cardTitle: 'What is it Like to be a Foster Parent? &#8211; A Guide for Ontario',
    thumbnail: '/assets/uploads/2026/02/foster1.jpg',
    excerpt: 'If you are considering fostering, it helps to understand what the role actually looks like once a child arrives in...',
    meta: 'Mar 3rd 2026 By Safe Harbours',
    related: ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton'],
  },
};

// Order of cards on the /resources index page.
export const indexOrder: string[] = ['best-childrens-foster-agencies-in-toronto', '5-best-childrens-foster-agencies-in-mississauga', '4-best-childrens-foster-agencies-in-hamilton', 'what-is-it-like-to-be-a-foster-parent-guide-for-ontario', 'is-it-hard-to-become-a-foster-parent-in-ontario', 'how-to-choose-a-foster-agency-a-guide-for-ontario', 'can-you-request-a-different-foster-child-if-it-isnt-working-out-yes', 'can-you-end-a-foster-placement-if-it-isnt-working-out-yes', 'eligibility-and-requirements-for-becoming-a-foster-parent-in-ontario'];
