// AUTO-GENERATED by scripts/images.mjs — widths of the AVIF/WebP variants
// available for each upload (used by src/lib/img.ts background image-set()).
export const imageVariants: Record<string, number[]> = {
  "/assets/theme/img/FAQ.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/theme/img/zig-zag.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/Family-Home-e1728610237634.png": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/Family2-1.png": [
    640,
    735
  ],
  "/assets/uploads/2024/10/Frame-34130-1-e1730335908622.jpg": [
    640,
    828
  ],
  "/assets/uploads/2024/10/Frame-34130-2.jpg": [
    640,
    834
  ],
  "/assets/uploads/2024/10/Frame-34130-3.jpg": [
    640,
    834
  ],
  "/assets/uploads/2024/10/Frame-34130-4.jpg": [
    640,
    834
  ],
  "/assets/uploads/2024/10/GetStarted-Global.png": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/Hero-ContactUs-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/Hero-Mobile-1-scaled-e1728576191410.jpg": [
    524
  ],
  "/assets/uploads/2024/10/Hero-Section-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/Interview-ContactUs.png": [
    640,
    1024,
    1440,
    1707
  ],
  "/assets/uploads/2024/10/blog-hero-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/famly-icon.png": [
    146
  ],
  "/assets/uploads/2024/10/hands-light-icon.png": [
    146
  ],
  "/assets/uploads/2024/10/heart-dark-icon-e1729696124837.png": [
    123
  ],
  "/assets/uploads/2024/10/heart-people-2.png": [
    132
  ],
  "/assets/uploads/2024/10/heart-people-icon.png": [
    158
  ],
  "/assets/uploads/2024/10/heart-people.png": [
    142
  ],
  "/assets/uploads/2024/10/house-icon-e1729732863639.png": [
    147
  ],
  "/assets/uploads/2024/10/shutterstock_1575539629-1-1.jpg": [
    640,
    1024,
    1440,
    1913
  ],
  "/assets/uploads/2024/10/shutterstock_1575539629-1.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2024/10/shutterstock_1575539629-2-1.jpg": [
    640,
    1024,
    1440,
    1917
  ],
  "/assets/uploads/2024/10/shutterstock_1575539629-2-2.jpg": [
    640,
    1024,
    1440,
    1917
  ],
  "/assets/uploads/2024/10/shutterstock_1575539629-2.png": [
    640,
    1024,
    1440,
    1917
  ],
  "/assets/uploads/2024/11/ChrisWilson.png": [
    640,
    844
  ],
  "/assets/uploads/2024/11/ChrisWilsonFounder-1.png": [
    393
  ],
  "/assets/uploads/2024/11/CollegeKids-NoCircle.png": [
    640,
    1024,
    1440,
    1512
  ],
  "/assets/uploads/2024/11/Group-34236.png": [
    640,
    1024,
    1266
  ],
  "/assets/uploads/2024/11/Group-34237.png": [
    522
  ],
  "/assets/uploads/2024/11/Group-34243.png": [
    576
  ],
  "/assets/uploads/2024/11/Group-34244.png": [
    537
  ],
  "/assets/uploads/2024/11/Group-34245.png": [
    399
  ],
  "/assets/uploads/2024/11/Group-34246.png": [
    640,
    789
  ],
  "/assets/uploads/2024/11/Group-34247.png": [
    640,
    732
  ],
  "/assets/uploads/2024/11/JamieMoreau.png": [
    393
  ],
  "/assets/uploads/2024/11/MattPearson.png": [
    393
  ],
  "/assets/uploads/2024/11/MichellePowell.png": [
    393
  ],
  "/assets/uploads/2025/10/Frame-3412.png": [
    640,
    834
  ],
  "/assets/uploads/2025/10/Frame-34158.png": [
    640,
    834
  ],
  "/assets/uploads/2025/10/compensation.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2025/10/eab76d9f553da936be9cfefd6ce5cef1c9a6d7db-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2025/10/getting-started.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2025/10/right-for-you.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2025/10/sdds-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2025/10/sfh-prof.jpg": [
    97
  ],
  "/assets/uploads/2026/02/best_foster1.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/best_foster2.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/best_foster3.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/foster1.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/foster2.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/foster3.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/foster6.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/foster_worried1.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/02/foster_worried2.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/035813eebf0eac33b0b47c9d24a3d67deab53f5e.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/2bac0df17bc1a8a882136427f4099e15b6120f6b-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2026/03/3f418b7c87d1a812cf20290b21a59a2e2d9e5b91-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2026/03/41387592358f78c8b433c64a1485a4bbdfdb9d35.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/669def284027a68a70608dbffae6eb4704a46e6e.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/66b1af25c30d9d7a7baaee18f6429a5146bd7149.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/744be7c9db465ec9747282c48204324f05722533.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/888b5ad8a4f4066bf92c1fead3fe1ba7fa5c6497.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.38.54-PM.png": [
    640,
    891
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.39.16-PM.png": [
    640,
    1024,
    1056
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.39.23-PM.png": [
    640,
    1024,
    1054
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.39.58-PM.png": [
    640,
    1024,
    1202
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.40.12-PM.png": [
    640,
    912
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.40.19-PM.png": [
    640,
    915
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.40.34-PM.png": [
    640,
    909
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.40.44-PM.png": [
    640,
    912
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.40.53-PM.png": [
    640,
    1024,
    1050
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.41.09-PM.png": [
    640,
    918
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.41.15-PM.png": [
    640,
    916
  ],
  "/assets/uploads/2026/03/Screenshot-2026-03-18-at-12.41.53-PM.png": [
    640,
    923
  ],
  "/assets/uploads/2026/03/a269d1361b8e1e75baef9b9df61879030ea1f6ff.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/a51b6418a4782ba5ce12a05da0e9b712c4132bd8.jpg": [
    640,
    1000
  ],
  "/assets/uploads/2026/03/bf10a2c2933ae4717c30d69eb45a7ca3c20ab027-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2026/03/d0ca6dd145296ad98dbb5388468b0fd667b37c36-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ],
  "/assets/uploads/2026/03/shutterstock_1575539629-2-1-scaled.jpg": [
    640,
    1024,
    1440,
    1920
  ]
};
