#!/usr/bin/env python3
# Generates db/seed-contact.sql — the Contact Us page as blocks (slot 'main'):
# contact hero (info + form), map, logos. Run:
#   python3 db/gen-seed-contact.py > db/seed-contact.sql
import json, re, os

U = "/assets/uploads"
MIRROR = os.path.join(os.path.dirname(__file__), "..", "_mirror")

def img(avif, webp, jpg):
    return {"avif": avif, "webp": webp, "jpg": jpg}

contact = open(os.path.join(MIRROR, "contact-us.main.html"), encoding="utf-8").read()
m = re.search(r'data-src="([^"]+)"', contact)
map_embed = m.group(1) if m else ""

blocks = []
blocks.append(("contactHero", {
    "heading": "Contact Us",
    "phone": "905-294-2137",
    "email": "info@safeharbours.ca",
    "address": '<span style="white-space:nowrap">517 Upper Sherman Ave.,</span><br>Hamilton, Ontario,  <span style="white-space:nowrap">L8V 3L7</span>',
    "bg": "image-set(url('%s/2024/10/Hero-ContactUs-scaled-1920.avif') type('image/avif'), url('%s/2024/10/Hero-ContactUs-scaled-1920.webp') type('image/webp'), url('%s/2024/10/Hero-ContactUs-scaled.jpg'))" % (U, U, U),
}))
blocks.append(("map", {"embed": map_embed}))
logos = [
    {"img": img("%s/2024/11/Group-34247-640.avif 640w" % U, "%s/2024/11/Group-34247-640.webp 640w" % U, "%s/2024/11/Group-34247.png" % U)},
    {"img": img("%s/2024/11/Group-34246-640.avif 640w" % U, "%s/2024/11/Group-34246-640.webp 640w" % U, "%s/2024/11/Group-34246.png" % U)},
    {"img": img("%s/2024/11/Group-34245-399.avif 399w" % U, "%s/2024/11/Group-34245-399.webp 399w" % U, "%s/2024/11/Group-34245.png" % U)},
    {"img": img("%s/2024/11/Group-34244-537.avif 537w" % U, "%s/2024/11/Group-34244-537.webp 537w" % U, "%s/2024/11/Group-34244.png" % U)},
    {"img": img("%s/2024/11/Group-34243-576.avif 576w" % U, "%s/2024/11/Group-34243-576.webp 576w" % U, "%s/2024/11/Group-34243.png" % U)},
    {"img": img("%s/2024/11/Group-34237-522.avif 522w" % U, "%s/2024/11/Group-34237-522.webp 522w" % U, "%s/2024/11/Group-34237.png" % U)},
    {"img": img("%s/2024/11/Group-34236-640.avif 640w, %s/2024/11/Group-34236-1024.avif 1024w" % (U, U), "%s/2024/11/Group-34236-640.webp 640w, %s/2024/11/Group-34236-1024.webp 1024w" % (U, U), "%s/2024/11/Group-34236.png" % U)},
]
blocks.append(("logos", {"heading": "Referral Partners", "logos": logos}))

print("-- Generated by db/gen-seed-contact.py — Contact Us page as blocks.")
print("DELETE FROM content_blocks WHERE page='contact-us';")
for pos, (kind, body) in enumerate(blocks):
    j = json.dumps(body, ensure_ascii=False).replace("'", "''")
    print("INSERT INTO content_blocks (page,slot,kind,body,position,state,updated_at) VALUES ('contact-us','main','%s','%s',%d,'published','');" % (kind, j, pos))
