#!/usr/bin/env python3
# Generates db/seed-textpages.sql — the long-form content pages (privacy, terms)
# as a single editable textBlock each, with the body lifted verbatim from the
# mirror. Run: python3 db/gen-seed-textpages.py > db/seed-textpages.sql
import json, re, os, sys, html as htmllib

MIRROR = os.path.join(os.path.dirname(__file__), "..", "_mirror")

def cell_content(html):
    """Return the inner HTML of the .cell.large-10 column (balanced-div scan)."""
    m = re.search(r'<div class="cell large-10">', html)
    start = m.end()
    depth = 1
    i = start
    for tok in re.finditer(r'<div\b|</div>', html[start:]):
        depth += 1 if tok.group() == '<div' else -1
        if depth == 0:
            return html[start:start + tok.start()].strip()
    return html[start:].strip()

def split_heading(inner):
    """First <h1> → heading text; everything after it → body HTML."""
    m = re.search(r'<h1[^>]*>(.*?)</h1>', inner, re.S)
    if not m:
        return "", inner
    heading = htmllib.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip()
    body = inner[m.end():].strip()
    return heading, body

PAGES = [("privacy-policy", "privacy-policy"), ("terms-conditions", "terms-conditions")]

print("-- Generated by db/gen-seed-textpages.py — privacy + terms as editable textBlocks.")
for page, mirror in PAGES:
    html = open(os.path.join(MIRROR, mirror + ".main.html"), encoding="utf-8").read()
    heading, body = split_heading(cell_content(html))
    body = re.sub(r'\sdata-gc-[a-z-]+="[^"]*"', '', body)  # drop editor cruft attrs
    j = json.dumps({"heading": heading, "body": body}, ensure_ascii=False).replace("'", "''")
    print("DELETE FROM content_blocks WHERE page='%s';" % page)
    print("INSERT INTO content_blocks (page,slot,kind,body,position,state,updated_at) VALUES ('%s','main','textBlock','%s',0,'published','');" % (page, j))
    print("-- %s: heading=%r body=%d chars" % (page, heading, len(body)), file=sys.stderr)
