#!/usr/bin/env python3
# Generates a seed for a hero + zig-zag/editorial page (program-description,
# complaints) by parsing the mirror: hero → hero block, each .zig-zag section →
# a steps block (sectionClass preserved; .no-numbers hides the count via CSS),
# any other <section> → a richSection. Usage:
#   python3 db/gen-seed-zigzag-page.py program-description > db/seed-program.sql
import re, json, os, sys, html as htmllib

page = sys.argv[1]
MIRROR = os.path.join(os.path.dirname(__file__), "..", "_mirror")
html = open(os.path.join(MIRROR, page + ".main.html"), encoding="utf-8").read()

def balanced_div(s, openend):
    depth = 1
    for tok in re.finditer(r'<div\b|</div>', s[openend:]):
        depth += 1 if tok.group() == '<div' else -1
        if depth == 0:
            return s[openend:openend + tok.start()], openend + tok.end()
    return s[openend:], len(s)

def text_of(h):
    return htmllib.unescape(re.sub(r'<[^>]+>', '', h)).strip()

def clean_ws(h):
    return re.sub(r'>\s+<', '><', h.strip()).strip()

def parse_picture(h):
    pic = re.search(r'<picture>(.*?)</picture>', h, re.S)
    if not pic:
        return {}
    p, out = pic.group(1), {}
    a = re.search(r'<source type="image/avif" srcset="([^"]+)"', p)
    w = re.search(r'<source type="image/webp" srcset="([^"]+)"', p)
    im = re.search(r'<img[^>]*\ssrc="([^"]+)"', p)
    if a: out["avif"] = a.group(1)
    if w: out["webp"] = w.group(1)
    if im: out["jpg"] = im.group(1)
    wm, hm = re.search(r'\swidth="(\d+)"', p), re.search(r'\sheight="(\d+)"', p)
    if wm: out["w"] = int(wm.group(1))
    if hm: out["h"] = int(hm.group(1))
    return out

def parse_rows(sec):
    rows = []
    for m in re.finditer(r'<div class="zig-zag-row\s*([^"]*)">', sec):
        reverse = 'reverse' in m.group(1)
        inner, _ = balanced_div(sec, m.end())
        img = parse_picture(inner)
        cm = re.search(r'<div class="zig-zag-content[^"]*">', inner)
        cinner, _ = balanced_div(inner, cm.end())
        cinner = re.sub(r'<span class="row-count">.*?</span>', '', cinner, flags=re.S)
        hm = re.search(r'<(h[1-6])[^>]*>(.*?)</\1>', cinner, re.S)
        if hm:
            heading, body = text_of(hm.group(2)), cinner[hm.end():]
        else:
            heading, body = '', cinner
        rows.append({"reverse": reverse, "heading": heading, "body": clean_ws(body), "img": img})
    return rows

blocks = []

# hero
hm = re.search(r'<div class="page-hero\s*([^"]*)">', html)
hinner, _ = balanced_div(html, hm.end())
variant = hm.group(1).strip()
cm = re.search(r'<div class="content">', hinner)
content = balanced_div(hinner, cm.end())[0] if cm else ''
lead_m = re.search(r'<p class="lead">(.*?)</p>', content, re.S)
h1_m = re.search(r'<h1>(.*?)</h1>', content, re.S)
hero = {
    "lead": text_of(lead_m.group(1)) if lead_m else "",
    "heading": text_of(h1_m.group(1)) if h1_m else "",
    "intro": clean_ws(content[h1_m.end():]) if h1_m else "",
    "bg": "", "variant": variant,
}
bg_m = re.search(r'<div class="background-image" style="background-image:\s*(.*?);?\s*"', hinner, re.S)
if bg_m:
    hero["bg"] = bg_m.group(1).strip()
blocks.append(("hero", hero))

# sections, in document order
for m in re.finditer(r'<section\b[^>]*class="([^"]*)"[^>]*>', html):
    cls = m.group(1).strip()
    depth, sec = 1, None
    for tok in re.finditer(r'<section\b|</section>', html[m.end():]):
        depth += 1 if tok.group() == '<section' else -1
        if depth == 0:
            sec = html[m.start():m.end() + tok.start()]
            break
    if sec is None:
        continue
    if 'zig-zag' in cls:
        sc = ' '.join(c for c in cls.split() if c != 'zig-zag')
        blocks.append(("steps", {"heading": "", "steps": parse_rows(sec), "sectionClass": sc}))
    else:
        gm = re.search(r'<div class="grid-container">', sec)
        ginner = balanced_div(sec, gm.end())[0] if gm else sec
        blocks.append(("richSection", {"sectionClass": cls, "body": clean_ws(ginner)}))

print("-- Generated by db/gen-seed-zigzag-page.py %s" % page)
print("DELETE FROM content_blocks WHERE page='%s';" % page)
for pos, (kind, body) in enumerate(blocks):
    j = json.dumps(body, ensure_ascii=False).replace("'", "''")
    print("INSERT INTO content_blocks (page,slot,kind,body,position,state,updated_at) VALUES ('%s','main','%s','%s',%d,'published','');" % (page, kind, j, pos))
print("-- %s: %d blocks (%s)" % (page, len(blocks), ', '.join(k for k, _ in blocks)), file=sys.stderr)
